apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-fed-deployment
  labels:
    app: fiap-fed-travel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-fed-travel
  template:
    metadata:
      labels:
        app: fiap-fed-travel
    spec:
      containers:
        - name: fiap-fed-travel
          image: "marcocouzin/fiap_travel_fed"
          ports:
            - name: http
              containerPort: 80
